# <%
# virtual_network_name = '<REPLACE_BY_NETWORK_NAME>'
# subnet_name = '<REPLACE_BY_SUBNET_NAME>'
# rootdomain = "<REPLACE_BY_ROOT_DOMAIN_NAME>"
# dns = '<REPLACE_BY_DNS_SERVER_IPS>'
# bosh_public_ip = '<REPLACE_BY_BOSH_PUBLIC_IP>'
# subscription_id = '<REPLACE_BY_SUBSCIPTION_ID>'
# tenant_id = '<REPLACE_BY_TENANT_ID>'
# client_id = '<REPLACE_BY_CLIENT_ID>'
# client_secret = '<REPLACE_BY_CLIENT_SECRET>'
# resource_group_name = '<REPLACE_BY_RESOURCE_GROUP_NAME>'
# storage_account_name = '<REPLACE_BY_STORAGE_ACCOUNT_NAME>'
# storage_access_key = '<REPLACE_BY_STORAGE_ACCESS_KEY>'
# %>

---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=255.3
  sha1: 1a3d61f968b9719d9afbd160a02930c464958bf4
- name: bosh-azure-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-azure-cpi-release?v=7
  sha1: 8df7b79458335188a1ecab83cf5ef9a82366baeb

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent?v=3169
    sha1: ff13c47ac7ce121dee6153c1564bd8965edf9f59
  cloud_properties:
    instance_type: Standard_D1

disk_pools:
- name: disks
  disk_size: 20_000

networks:
- name: public
  type: vip
  cloud_properties:
    tcp_endpoints:
    - "22:22"
    - "4222:4222"
    - "6868:6868"
    - "25250:25250"
    - "25555:25555"
    - "25777:25777"
    udp_endpoints:
    - "68:68"
    - "53:53"
- name: private
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns: [8.8.8.8]
    cloud_properties:
      virtual_network_name: <REPLACE_BY_NETWORK_NAME>
      subnet_name: <REPLACE_BY_SUBNET_NAME>

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: redis, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: cpi, release: bosh-azure-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: [10.0.0.4]
    default: [dns, gateway]
  - name: public
    static_ips: [<REPLACE_BY_BOSH_PUBLIC_IP>]

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    redis:
      listen_address: 127.0.0.1
      address: 127.0.0.1
      password: redis-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    registry:
      address: 10.0.0.4
      host: 10.0.0.4
      db: *db
      http: {user: admin, password: admin, port: 25777}
      username: admin
      password: admin
      port: 25777

    blobstore:
      address: 10.0.0.4
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: cpi
      max_threads: 10
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm, password: hm-password}

    hm:
      director_account: {user: hm, password: hm-password}
      resurrector_enabled: true

    azure: &azure
      environment: AzureCloud
      subscription_id: <REPLACE_BY_SUBSCIPTION_ID>
      tenant_id: <REPLACE_BY_TENANT_ID>
      client_id: <REPLACE_BY_CLIENT_ID>
      client_secret: <REPLACE_BY_CLIENT_SECRET>
      resource_group_name: <REPLACE_BY_RESOURCE_GROUP_NAME>
      storage_account_name: <REPLACE_BY_STORAGE_ACCOUNT_NAME>
      storage_access_key: <REPLACE_BY_STORAGE_ACCESS_KEY>
      ssh_user: vcap
      ssh_certificate: |
        <RELACE_BY_BOSH_PUBLIC_CERT>

    agent: {mbus: "nats://nats:nats-password@10.0.0.4:4222"}

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: cpi, release: bosh-azure-cpi}

  ssh_tunnel:
    host: <REPLACE_BY_BOSH_PUBLIC_IP>
    port: 22
    user: vcap
    private_key: <REPLACE_BY_BOSH_PRIVATE_KEY_PATH> # Path relative to this manifest file

  mbus: https://mbus:mbus-password@<REPLACE_BY_BOSH_PUBLIC_IP>:6868

  properties:
    azure: *azure
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
